### ISSUE TITLE
Improve caching in workflow file

### ISSUE THREAD

**Issue by d-walsh** [All-Hands-AI/openhands-resolver#143]
Is it possible to speed up multiple runs of the workflow by adding caching

**Comment by neubig** [comment]
Good point, I think we can probably cache the install of packages at least.

**Comment by malhotra5** [comment]
I've attached one possible solution for caching the package installation

Another cache could be dedicated to the docker image itself. However, [Github only allows for 10GB of cache in a single repository](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy), so this may be unideal for some users

**Comment by neubig** [comment]
The new caching is great, the resolver starts much faster!
I think any remaining caching-related things can be tracked in issue #49, so let's close this one as finished.
