### ISSUE TITLE
"secrets: inherit" not working 

### ISSUE THREAD

**Issue by d-walsh** [All-Hands-AI/openhands-resolver#144]
It looks like this might be a known issue (https://github.com/actions/runner/issues/2709)

**Comment by neubig** [comment]
Could you elaborate a bit more on what is not working? We are using the workflow on other repos like https://GitHub.com/all-hands-ai/OpenHands and it seems to be functional there

**Comment by neubig** [comment]
Hmm, OK... The setup is working for us here:
https://github.com/All-Hands-AI/OpenHands/blob/main/.github/workflows/openhands-resolver.yml

But that might be because it's in the same github org or something? I'll try to poke around a little bit at this by using a different github repo, etc.

**Comment by neubig** [comment]
I was able to repro, working on it.

**Comment by neubig** [comment]
This was fixed by #152, so this file should now work: https://github.com/All-Hands-AI/openhands-resolver/blob/main/examples/openhands-resolver.yml
