### ISSUE TITLE
Github App implementation

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/openhands-resolver#155]
A personal access token is not sufficient to send PRs from a fork: https://github.com/neubig/pr-viewer/actions/runs/11209219632

We may need to rethink how things are done in github actions. One possibility is to create a github app: https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps

---
*This issue has been moved to All-Hands-AI/openhands#5050*

**Comment by xingyaoww** [comment]
Once this issue is resolved, we might be able to do https://github.com/All-Hands-AI/openhands-resolver/issues/202

**Comment by malhotra5** [comment]
This seems like a higher effort yet important task? I could take a shot at this. I'm thinking [probot](https://github.com/probot/probot) could be helpful to use. I'm also not too familiar with apps, will I have to transfer ownership to Openhands once its built?

**Comment by neubig** [comment]
Hey @malhotra5 , I can take this one (I've already started a little bit). If you're looking for other ones to do, I think that we're getting a few "job failed without logs" ones like this: https://github.com/All-Hands-AI/openhands-resolver/issues/233

I think they could be pretty valuable to debug if that'd be possible.
