### ISSUE TITLE
Add ability to resume session

### ISSUE THREAD

**Issue by Jacck** [All-Hands-AI/openhands-resolver#197]
I left the session overnight, I'm still on the session, I didnt close it. but LLM is not responding. Info from Ubuntu terminal: `2024-10-27 22:13:21,289 - INFO - AgentController task was cancelled
2024-10-27 22:13:21,292 - INFO - Session Finished
2024-10-27 22:14:08,595 - INFO - Session {number} and related resource have been removed due to inactivity.` How can I resume the session to continue work with same context?

---
*This issue has been moved to All-Hands-AI/openhands#5047*

**Comment by neubig** [comment]
Hmm, good question. Right now this is not directly supported, unfortunately. As a workaround you can probably

1. cd into the appropriate sub-directory of the output directory (`cd output/patch_{issue_number}`)
2. commit the changed code
3. push a branch to the repo and open a PR
4. add a comment about what still needs to be implemented
5. run `resolve_issues.py` with `--issue-type pr`

I think it'd be good to have better session resume functionality in the future though.
