### ISSUE TITLE
Feature: support reading screenshots from Github Issue

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/openhands-resolver#213]
Right now our `IssueHandlerInterface` in `openhands_resolver/issue_definitions.py` have `def get_instruction(self, issue: GithubIssue, prompt_template: str, repo_instruction: str | None = None) -> str:` which is a little limited since it only has text.

We should:
1. Extend the `IssueHandlerInterface` to return not only instructions in the string but also all the links to screenshots in the original issue.
2. We should update all the tests for `get_instruction` accordingly
3. In `openhands_resolver/resolve_issues.py`, we should pass in `images_urls: list | None = None` to `MessageAction` as well.

**Comment by malhotra5** [comment]
I could take a shot at this :)

**Comment by neubig** [comment]
Fixed by #220 !
