### ISSUE TITLE
Github action is stalling on OpenHands repo when resolving PR comments

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/openhands-resolver#230]
On this issue, even after adding the `fix-me` label the PR is not replaced.

https://github.com/All-Hands-AI/OpenHands/pull/4671

**Comment by malhotra5** [comment]
Is there a link to the Github action logs?

**Comment by neubig** [comment]
No, I'm not sure it's even being activated...

**Comment by malhotra5** [comment]
Is it because the [openhands-resolver yaml](https://github.com/All-Hands-AI/OpenHands/blob/main/.github/workflows/openhands-resolver.yml) in Openhands hasn't been updated for pull request label events?

**Comment by neubig** [comment]
Awesome, thank you!

**Comment by neubig** [comment]
Fixed by #4712
