### ISSUE TITLE
allow the github-resolver github action to be triggered by comments on issues or PRs

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/openhands-resolver#232]
The workflow we provide here can be trigger with a github action like the one in examples/openhands-resolver.yml, where it responds to issues that have been tagged

Please modify our workflow so that it can also be triggered by comments on issues or PRs, but only if the comment contains `@openhands-agent` (the name must be configurable by the user of the Action)

This should pull in the original issue/PR text, as well as the new comment, as the text that's passed to the agent as a prompt. If the comment is on a PR, and the PR mentions an issue in the description, it should also pull in the text of the linked issue

---
*This issue has been moved to All-Hands-AI/openhands#5046*

**Comment by malhotra5** [comment]
I could take a shot at this one 🙂

**Comment by malhotra5** [comment]
@rbren wanted to clarify something

> This should pull in the original issue/PR text, as well as the new comment, as the text that's passed to the agent as a prompt. If the comment is on a PR, and the PR mentions an issue in the description, it should also pull in the text of the linked issue

Does this mean that when the macro, such as @openhands-agent, is added to a comment on an issue, we should only use the issue body and the specific comment with the macro as context, and ignore all other previous comments on the issue?

I'm concerned that excluding prior comments might lose valuable context that could aid in the resolution. Could you confirm if the goal is to isolate only the issue body and the macro-tagged comment, or if all previous comments should be included as context?

**Comment by rbren** [comment]
I'm good either way! So long as it has the context it needs
