### ISSUE TITLE
Logs are insufficient on litellm API errors

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/openhands-resolver#239]
In the following GitHub action, something is going wrong with an API call, but the logs are not sufficient to debug the problem. We should make sure that logs are effectively printed. 

https://github.com/PierrunoYT/OpenHands/actions/runs/11652322360/job/32443373978

---
*This issue has been moved to All-Hands-AI/openhands#5045*

**Comment by PierrunoYT** [comment]
![grafik](https://github.com/user-attachments/assets/d0e87fdb-2bcb-4f8d-bbcb-e28e7d6f5277)

**Comment by malhotra5** [comment]
I believe `Openhands` retry logs have been updated to also include the exceptions that are thrown? I think this [file](https://github.com/All-Hands-AI/OpenHands/blob/main/openhands/llm/retry_mixin.py#L46) contains the update
