### ISSUE TITLE
Allow the openhands-resolver to also read full comments from PR

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/openhands-resolver#276]
Right now i believe OpenHands resolver is able to read comments from issue (the _get_issue_comments function in openhands_resolver/issue_definitions.py), but not PR yet. It will be great to have this.

**Comment by neubig** [comment]
Hey @xingyaoww , I think I implemented this here: https://github.com/All-Hands-AI/openhands-resolver/pull/273
Is that what you were looking for?

**Comment by xingyaoww** [comment]
I was actually thinking about the normal comments that is not a result of start a "review" - like this one: https://github.com/All-Hands-AI/OpenHands/pull/4801#issuecomment-2461134051

**Comment by neubig** [comment]
Got it, thanks!
