### ISSUE TITLE
[Refactor]: Remove issue_number as input to resolver workflow

### ISSUE THREAD

**Issue by malhotra5** [All-Hands-AI/openhands-resolver#283]
It seems `github.event` is shared between the caller and callee for a reusable workflow? [Github docs](https://docs.github.com/en/actions/sharing-automations/reusing-workflows) don't make this explicit but a quick [test](https://github.com/NaturalAgents/NaturalAgents/actions/runs/11736993061/job/32697081807) indicates that this is the case (proven under the step workflow "set env variables"). 

Should we refactor `.github/workflows/openhands-resolver.yml` to remove `issue_number` as an input for workflow_call and also remove all instances of `input.issue_number`.

**Comment by neubig** [comment]
That sounds like a good idea, thanks!
