### ISSUE TITLE
[Bug]: Openhands always responds with "New OpenHands update" when updating PR

### ISSUE THREAD

**Issue by malhotra5** [All-Hands-AI/openhands-resolver#297]
~~In the following code block inside `openhands_resolver/send_pull_request.py`, an error seems to consistently occurring causing `comment_message` to always be "New OpenHands update"~~

When a general comment is left on a PR, `openhands-resolver` consistently responds with "New OpenHands update". It would be helpful to respond with a summary instead.

**Comment by neubig** [comment]
Fixed by #301?
